
name: Deploy docker image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
      
env:
  PACKAGE_PATH: '.'
  DOTNET_VERSION: '5.0.100'
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Run dotnet build and pulbish
      - name: dotnet build and publish
        run: |
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.PACKAGE_PATH }}/app' -r linux-x64

      # Login to dockerhub        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}         
          
      # Setup Docker Buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1      
        
      #Setup bot configuration
      - name: Setup bot configuratiotn
        run: |
          mkdir -p ./HalDiscrodBot.Console/Config
          mv ./app ./HalDiscrodBot.Console
          echo "$DISCORD_CONFIG" > ./HalDiscrodBot.Console/Config/config.json
        env:
          DISCORD_CONFIG: ${{ secrets.DISCORD_CONFIG }}
          
      # Build and push image
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./HalDiscrodBot.Console
          file: ./HalDiscrodBot.Console/Dockerfile
          push: true
          tags: augustogallitri/haldiscordbot:latest
          

        
      
      
    
